

logging:
  level:
    org.keycloak: DEBUG
    org.springframework.security: DEBUG
    com.julyseven.jaeho: DEBUG

spring:
  application:
    name: jaeho-project
  redis:
    host: localhost
    port: 6379
    username: jaeho-redis
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: '${keycloak.auth-server-url}/realms/${keycloak.realm}'
        registration:
          oidc:
            client-id: '${keycloak.resource}'
            client-secret: '${keycloak.credentials.secret}'
            scope:
              - openid
              - profile
              - email

keycloak:
  realm: jaeho
  resource: jaeho-client
  auth-server-url: 'http://localhost:9000/auth'
  credentials:
    secret: 'mp07f2RaVOypqXLwer6S0WhXlh14ISpw'
