

logging:
  level:
    com.julyseven.jaeho: DEBUG

spring:
  application:
    name: jaeho-project
  redis:
    host: localhost
    port: 6379
    username: jaeho-redis
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: 'http://localhost:9000/auth/realms/master'
        registration:
          oidc:
            client-id: jaeho-client
            client-secret: jaeho-client
            scope:
              - openid
              - profile
              - email
    
