
spring:
  application:
    name: jaeho-project
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: 'http://localhost:9000/auth/realms/master'
        registration:
          oidc:
            client-id: jaeho-client
            client-secret: sCMQZdkQO2SJMmjRk5zW22y3EMFmO5j9
            scope:
              - openid
              - profile
              - email
